version: '3.9'

services:
  frontend:
    container_name: frontend-${APP_ENV}
    build: ./frontend
    volumes:
      - ./frontend:/app
    env_file:
      - ./.env.dev
    depends_on:
      - backend
    restart: always
    ports:
      - ${FRONTEND_MAPPED_PORT}:3000
  backend:
    container_name: backend-${APP_ENV}
    build: ./backend
    volumes:
      - ./backend:/code
      - ./frontend/build/:/code/static/frontend
    env_file:
      - ./.env.dev
    restart: always
    ports:
      - ${BACKEND_MAPPED_PORT}:8000
