version: '3.9'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code
    env_file:
      - ./.env
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/code
      - ./frontend/build/:/code/static/frontend
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
